create table if not exists users (
  id bigint generated by default as identity primary key,
  phone text unique,
  password text,
  username text,
  avatar text,
  balance numeric default 0,
  points integer default 0,
  sex text,
  is_agent integer default 0,
  open_id text,
  token text,
  created_at timestamptz default now()
);

create table if not exists product_categories (
  id bigint generated by default as identity primary key,
  cate_name text not null,
  icon text,
  sort integer default 0,
  created_at timestamptz default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  cate_id bigint references product_categories(id),
  product_name text not null,
  product_grade text,
  premium numeric default 0,
  exchange_price numeric default 0,
  dismantle_price numeric default 0,
  shipping_fee numeric default 0,
  store_page_icon text,
  product_detail_ad_image text,
  product_detail_images jsonb default '[]'::jsonb,
  show_store integer default 1,
  is_recommend boolean default false,
  is_hot boolean default false,
  created_at timestamptz default now()
);

create table if not exists product_boxes (
  id bigint generated by default as identity primary key,
  box_id bigint unique,
  name text not null,
  description text,
  img_src text,
  bg_type integer default 1,
  icon_type integer default 1,
  price numeric default 0,
  first_price numeric default 0,
  discount_price numeric default 0,
  prize_price_limit text,
  type integer default 1,
  detail_img text,
  sort integer default 0,
  created_at timestamptz default now()
);

create table if not exists product_box_items (
  id bigint generated by default as identity primary key,
  box_id bigint references product_boxes(id) on delete cascade,
  product_id bigint references products(id),
  draw_weight integer default 1,
  sort integer default 0,
  created_at timestamptz default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_no text unique,
  user_id bigint references users(id),
  box_id bigint references product_boxes(id),
  order_type integer,
  status integer default 0,
  total_price numeric default 0,
  shipping_fee numeric default 0,
  total_points numeric default 0,
  exchange_total_points numeric default 0,
  product_count integer default 0,
  product_list jsonb default '[]'::jsonb,
  exchange_list jsonb default '[]'::jsonb,
  address jsonb,
  content text,
  detail_img text,
  expire_time timestamptz,
  created_at timestamptz default now()
);

create table if not exists user_box_products (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  product_id bigint references products(id),
  source_order_no text,
  status integer default 0,
  -- 0 pending draw/open, 1 available, 2 consignment, 3 sold, 4 collected, 5 dismantled
  price numeric default 0,
  sell_price numeric default 0,
  product_snapshot jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists consignment_orders (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  user_box_product_id bigint references user_box_products(id),
  status integer default 0,
  -- 0 selling, 1 sold, 2 canceled
  sell_price numeric default 0,
  product_snapshot jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists banners (
  id bigint generated by default as identity primary key,
  type integer,
  box_id bigint,
  img_src text,
  detail_img text,
  sort integer default 0,
  created_at timestamptz default now()
);

create index if not exists idx_products_cate_id on products(cate_id);
create index if not exists idx_box_items_box_id on product_box_items(box_id);
create index if not exists idx_user_box_products_status on user_box_products(status);
create index if not exists idx_consignment_orders_status on consignment_orders(status);

alter table users enable row level security;
alter table product_categories enable row level security;
alter table products enable row level security;
alter table product_boxes enable row level security;
alter table product_box_items enable row level security;
alter table orders enable row level security;
alter table user_box_products enable row level security;
alter table consignment_orders enable row level security;
alter table banners enable row level security;

drop policy if exists "public read product categories" on product_categories;
create policy "public read product categories" on product_categories
  for select using (true);

drop policy if exists "public read products" on products;
create policy "public read products" on products
  for select using (true);

drop policy if exists "public read product boxes" on product_boxes;
create policy "public read product boxes" on product_boxes
  for select using (true);

drop policy if exists "public read product box items" on product_box_items;
create policy "public read product box items" on product_box_items
  for select using (true);

drop policy if exists "public read banners" on banners;
create policy "public read banners" on banners
  for select using (true);
