create table if not exists users (
  id bigint generated by default as identity primary key,
  phone text unique,
  password text,
  username text,
  avatar text,
  balance numeric default 0,
  points integer default 0,
  sex text,
  is_agent integer default 0,
  open_id text,
  token text,
  created_at timestamptz default now()
);

create table if not exists product_categories (
  id bigint generated by default as identity primary key,
  cate_name text not null,
  icon text,
  sort integer default 0,
  created_at timestamptz default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  cate_id bigint references product_categories(id),
  product_name text not null,
  product_grade text,
  premium numeric default 0,
  exchange_price numeric default 0,
  dismantle_price numeric default 0,
  shipping_fee numeric default 0,
  store_page_icon text,
  product_detail_ad_image text,
  product_detail_images jsonb default '[]'::jsonb,
  show_store integer default 1,
  created_at timestamptz default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_no text unique,
  order_type integer,
  status integer default 0,
  total_price numeric default 0,
  shipping_fee numeric default 0,
  total_points numeric default 0,
  exchange_total_points numeric default 0,
  product_count integer default 0,
  product_list jsonb default '[]'::jsonb,
  exchange_list jsonb default '[]'::jsonb,
  address jsonb,
  content text,
  detail_img text,
  expire_time timestamptz,
  created_at timestamptz default now()
);

create table if not exists banners (
  id bigint generated by default as identity primary key,
  type integer,
  box_id bigint,
  img_src text,
  detail_img text,
  sort integer default 0,
  created_at timestamptz default now()
);

create table if not exists product_boxes (
  id bigint generated by default as identity primary key,
  box_id bigint,
  name text not null,
  description text,
  img_src text,
  bg_type integer,
  icon_type integer,
  price numeric default 0,
  first_price numeric default 0,
  discount_price numeric default 0,
  prize_price_limit text,
  type integer default 1,
  detail_img text,
  sort integer default 0,
  created_at timestamptz default now()
);
